#!/usr/bin/env bash
# Create a new python environment on a Mac to run psychopy experiments
# Requirements:
# - anaconda (brew cask install anaconda)

# Create a lab environment
source ~/anaconda3/bin/activate
conda create -f environment.yml
source activate lab
